server:
  port: 8082
  servlet:
    session:
      cookie:
        http-only: true # 浏览器脚本无法访问cookie 安全
        secure: false #必须用https才能发送cookie

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccims?allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 2326
    schema:
  web:
    resources:
      static-locations: classpath:templates/
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


# actable的配置信息
actable:
  table:
    auto: update
  model:
    pack: com.zhangxiang.ccims.entity
  database:
    type: mysql


mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml,classpath:mapper/*.xml
  type-enums-package: classpath*:com/zhangxiang.ccims/enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

my_config:
  material:
    path: C:\Users\hxying\Desktop\ccims\material

  homework:
    path: C:\Users\hxying\Desktop\ccims\material\homework

